name: "Build"

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        name: "Checkout repositories"
        with:
          submodules: recursive

      - name: "Run build task"
        run: |
          brew install go-task
          task build-all
          tar --zstd -cvf mediakit-dist.tar.zst ./dist

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: mediakit-build
          path: ./mediakit-dist.tar.zst
